### ISSUE TITLE
Current bugs to be fixed 4/25/2020

### ISSUE THREAD

**Issue by JosephZhang-LDL** [InternInit/TII_React_App#1]
- When the state updates in the pageInternshipInformation, the value lags by one character behind what the user is typing
- The validation rule for input types does not work as expected

**Comment by JosephZhang-LDL** [comment]
**FIXED**
Fixed the state update

**TO FIX**
- Find a way to bold all the labels for the form input boxes
- Change the extracurricular input to make it so that there is standardized name: description input that can be added to
- Formatting for the Times to Work Section

**Comment by tm1287** [comment]
See new issues per industry standard.
