### ISSUE TITLE
Fake data pool of company for student to interact with 

### ISSUE THREAD

**Issue by brandonlu1** [InternInit/TII_React_App#68]
the current dashboard is filled with dummy information, it need to be switched to information from the database

**Comment by tm1287** [comment]
ES connected: see commit ef4371b7a892111478c3936bd41c0296001a614f

**Comment by tm1287** [comment]
TODO: Rewrite load in logic to pull from ES index

**Comment by tm1287** [comment]
Resolved: see commit ef4371b7a892111478c3936bd41c0296001a614f
